### ISSUE TITLE
Order option is needed in searchRead function

### ISSUE THREAD

**Issue by tsogoo** [vettloffah/odoo-await#12]

**Comment by vettloffah** [comment]
The only options [documented by Odoo](https://www.odoo.com/documentation/14.0/webservices/odoo.html) are `offset` and `limit`. Let me know if you have any sources that show order as an option? 

I will check out the source code when I have some time to see if it exists there.

**Comment by vettloffah** [comment]
Found this in a quick search: https://stackoverflow.com/questions/43984988/odoo-php-how-can-i-set-order-by-in-api-call

So yes, it seems to be supported. Will add this to a future release.

**Comment by vettloffah** [comment]
Merged #13 for version 2.2, added test and readme for the feature.
