### ISSUE TITLE
Remove the console.log from the connect function

### ISSUE THREAD

**Issue by MohammedAlhalwachi** [vettloffah/odoo-await#14]
Hi!
Thank you for maintaining this project.

Currently the connect function uses `console.log` which prints the message:
`Connected to Odoo with user ID: X`

So using the package in a CLI tool, prints out the message when ever connecting in the console. 
Perhaps, it would be better to remove the message and leave the option for the developer?

**Comment by vettloffah** [comment]
Thanks, this will be included in the next release
