### ISSUE TITLE
Change "url" to "baseUrl" in the README

### ISSUE THREAD

**Issue by soyantonio** [vettloffah/odoo-await#2]
## Description

According to the current documentation, to change the Odoo url, the `url` should be changed when the Object is constructed.

```
const odoo = new Odoo({
    url: 'http://other-domain',
    port: 8069,
    db: 'odoo_db',
    username: 'admin',
    password: 'admin'
});

await odoo.connect();
```

## Expected behavior 

Odoo service should try to connect to `http://other-domain`

## Actual behavior 

Odoo service tries to connect to `http://localhost`. The reason is at `lib/index.js`, **url** field is not present

https://github.com/vettloffah/odoo-await/blob/b5cc5bec557745cf5be15d0909bf3c3f5311f9a2/lib/index.js#L24-L32

If **baseURL** will be the chosen name, then the README should be changed. This will reduce the friction to use this module

**Comment by vettloffah** [comment]
Thanks for pointing that out. I've updated the readme.
