### ISSUE TITLE
Update the README for testing

### ISSUE THREAD

**Issue by ajmas** [vettloffah/odoo-await#24]
Having recently made changes to for #19, I was unable to establish the right testing environment.

The docs indicate:

> The default test will run through basic CRUD functions, creating a `res.partner` record, updating it, reading it, and deleting it. Uses Mocha and Should as dependencies.
>
>If you are using default db name `"odoo_db"`, username `"admin"`, password `"admin"`, and port `8069` on `"http://localhost"`:
> ```shell script
> $ npm test 
> ```
> If you aren't using the defaults, pass the variables in command line with environment variables:
>  ```shell script
> $ ODOO_DB=mydatabase ODOO_USER=myusername ODOO_PW=mypassword ODOO_PORT=8080 > ODOO_BASE_URL=https://myodoo.com npm test 
> ```

I suspect there is a test oriented Odoo instance setup missing, but I can't say for sure. Updated steps here could also be useful for future setup of CI, via Github Workflow.

**Comment by vettloffah** [comment]
I removed some tests in version 3.1.0 that would only work on an empty odoo isntance. I believe it should work now with the instructions provided. Let me know if you try it out and still have issues.
