### ISSUE TITLE
Logging request data?

### ISSUE THREAD

**Issue by ajmas** [vettloffah/odoo-await#25]
Is there any way to log the raw xml-rpc request data generated by this package? We are being asked to keep a log history of the transmissions, for ops reasons.

**Comment by vettloffah** [comment]
I don't think the xml-rpc package has a logging feature for the raw data. Did you ever find a solution?

**Comment by ajmas** [comment]
xml-rpc did have something, though I had debated just using a logging proxy to consolidate all HTTP logs. This partly due to limitations of logging with Axios, that we were using in another part of the app. 

I’ll share what I found on xml-rpc later. On my phone.
