### ISSUE TITLE
Replace depricated `querystring` with `URLSearchParams` API

### ISSUE THREAD

**Issue by w1jp** [vettloffah/odoo-await#26]
...to get rid of warning:
```npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.```

**Comment by vettloffah** [comment]
I checked this out - querystring is a dependency of 'url' package.
So I will change to the global URL and remove the url package and publish shortly.

**Comment by vettloffah** [comment]
This has been updated in version 3.1.0
