### ISSUE TITLE
update with context

### ISSUE THREAD

**Issue by DonsWayo** [vettloffah/odoo-await#28]
Hi, 

Is posible to update a model with context? 

like this:

 odoo.update('product.template', 222, {short_description: '3M Hazard Warning Tape ', context: { lang: 'en_GB' }});

I get a true response, but not updated on odoo. Can do in some way?

thanks

**Comment by vettloffah** [comment]
That's not currently built into the library.

You could try using the ` execute_kw(model, method, params)` method as a work around.

something like:
```js
await odoo.execute_kw('product.template', 'update', [ [222 , {short_description: "3M Hazard Warning Tape"}, { context: { lang: 'en_GB'  } } ] ]
```

Could you let me know if that works?

**Comment by vettloffah** [comment]
@DonsWayo the "marshal none" error is actually just odoo not returning anything, which is not actually usually an error. It's because the XML RPC settings in odoo by default are set to not allow it to return nothing. You can catch this error and ignore it.
