### ISSUE TITLE
[Question] Can this be used as Public User

### ISSUE THREAD

**Issue by mordechaim** [vettloffah/odoo-await#32]
I'm looking into building a headless e-commerce platform with Odoo as the backend. This library seems like a perfect fit but I'm not sure one thing.

One of the requirements of course is to be able to add to cart without logging in. Does this library strictly require an Odoo user or can this work in such a setting. (The question is really about the External API in general.)

**Comment by vettloffah** [comment]
Requires odoo user authentication
