### ISSUE TITLE
Allow using any supported comparison operators in `domain`

### ISSUE THREAD

**Issue by richrd** [vettloffah/odoo-await#6]
Currently passing in `domain` for the search methods just passes the key and value as an equality comparison. It'd be useful to allow using other operators as listed here: https://www.odoo.com/documentation/14.0/reference/orm.html#search-domains
To avoid breaking the current API maybe it could work by passing in an object as the value. So in addition to this:
```
[
    {unit_price: 100},
]
```
it could also accept something like this to allow setting the operator:
```
[
    {unit_price: {
        operator: '>',
        value: 100,
    }},
]
```

On the other hand it might be more flexible to have a separate advanced search method that allows providing a completely custom domain structure. The docs talk about being able to use `AND` and `OR` too and shows an example about it, but I'm not sure if that is supported through XML RPC. https://www.odoo.com/documentation/14.0/reference/orm.html#reference-orm-domains

Any thoughts? I could make a PR if there's interest.

**Comment by vettloffah** [comment]
This is something I didn't consider but actually just came across it myself this week.

I think a nice solution would be the default to assume it is '=', but if an object is supplied like you suggested, any operator could be used.

A current work around is to use the `execute_kw` method:

```js
matches = await this.odoo.execute_kw('res.partner', 'search', [
      [[ ["name", "ilike", name], ["email","=","someemail@example.com"] ]]
    ])
```

I could spend some time on this in a week or two, but if you would like to submit a PR that would be great.

Thanks!

**Comment by richrd** [comment]
Thanks for the work around, I think I'll use that for now. I like the convenience of the dedicated methods though so I'll see if I have time to make a PR at some point. I was thinking the same about defaulting to `=`. It's nice and convenient, and I'd rather not be making breaking changes, there's enough of that in the JS world already :slightly_smiling_face:

**Comment by pumppi** [comment]
We been working with some query filters for this case. I will send example when it's ready. 
Thanks for good lib!

**Comment by vettloffah** [comment]
@pumppi cool please do share!

**Comment by vettloffah** [comment]
@pumppi just making you sure you saw the new feature I added. Can now use an array for the comparison operators.

**Comment by richrd** [comment]
Thanks! Really appreciate the active work on this lib :)
