### ISSUE TITLE
What is the minimal supported Odoo version ?

### ISSUE THREAD

**Issue by crapougnax** [vettloffah/odoo-await#7]
Thank you for this package that could save my day.

What is the minimal supported version of Odoo? I can't find any indication of that anywhere. 

I suspect it's beyond v12 since you use the `authenticate` method instead of the `login`one.

**Comment by vettloffah** [comment]
Hi I have to be honest I’m not actually sure. I’ve only used it with 13+

If you figure out the answer please let us know.

Maybe i can add extra authentications methods for previous versions.

**Comment by crapougnax** [comment]
Fair enough, I was going to migrate to v13 or v14 CE anyway.

**Comment by vettloffah** [comment]
Version 12 - will update the readme
